apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: distributed-ml-pipeline-demo
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      parallelism: 1
      template:
        metadata:
          labels:
            app: distributed-ml-pipeline-demo
        spec:
          containers:
          - name: distributed-ml-pipeline-demo
            resources:
              limits:
                cpu: 2000m
                memory: 2048Mi
                ephemeral-storage: 2048Mi
            image: us-central1-docker.pkg.dev/alchemia-322204/docker-assets/distributed-ml-pipeline-demo:v1
            imagePullPolicy: Always
            command: ["python3"]
            args: ["main.py"]
          restartPolicy: Never
      backoffLimit: 0
